"""empty message

Revision ID: 530eb300af66
Revises: 45a5aff8548b
Create Date: 2025-03-05 19:41:35.195790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530eb300af66'
down_revision = '45a5aff8548b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favorite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
