"""empty message

Revision ID: 53edea47edd5
Revises: e20fb69a7623
Create Date: 2025-03-14 13:24:25.708971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53edea47edd5'
down_revision = 'e20fb69a7623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='planet_favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='planet_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planet_favorite_pkey')
    )
    op.drop_table('planet_favorites')
    # ### end Alembic commands ###
