"""empty message

Revision ID: 541c42e6b7a3
Revises: 83258cff558a
Create Date: 2025-03-05 19:06:21.176392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c42e6b7a3'
down_revision = '83258cff558a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
